/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Map;
import java.util.HashMap;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

        Map<Integer, Map<Integer, Integer>> graph = new HashMap<>();

        graph.put(1, Map.of(2, 1, 3, 1, 5, 1));
        graph.put(2, Map.of(4, 1));
        graph.put(3, Map.of(5, 1));
        graph.put(4, Map.of(3, 1));
        graph.put(5, new HashMap<>());

        int result = Dijkstra.shortestPath(graph, 1, 2);
        System.out.println("Shortest path: " + result);
        
        result = Dijkstra.shortestPath(graph, 1, 5);
        System.out.println("Shortest path: " + result);

        result = Dijkstra.shortestPath(graph, 2, 5);
        System.out.println("Shortest path: " + result);

        result = Dijkstra.shortestPath(graph, 5, 1);
        System.out.println("Shortest path: " + result);

        result = Dijkstra.shortestPath(graph, 2, 1);
        System.out.println("Shortest path: " + result);
    }
}
